### ISSUE TITLE
Sync data to Amazon-S3 compatible storage

### ISSUE THREAD

**Issue by AhmedBoutaraa57** [mongrov/react-native-timon#5]

**Comment by Sidahmeders** [comment]
closed in timon [v0.2.0](https://github.com/mongrov/react-native-timon/commit/6f8d8f15bbe9b1e634b1a1c2f8d246002c999d3e)

**Comment by AhmedBoutaraa57** [comment]
closed in [timon v0.2.0](https://github.com/mongrov/react-native-timon/commit/6f8d8f15bbe9b1e634b1a1c2f8d246002c999d3e)
